Setup environment & start rails server
BackerFounder/backme-cookbooks pull request #7
Opened 2020-10-28 03:48 UTC by requiemformemories

2020-10-28 06:37 UTC, elct9620 requested changes

2020-10-28 06:37 UTC, elct9620 commented on nginx/recipes/unicorn_config.rb
> +%w{sites-available sites-enabled}.each do |dir|
`sites-enabled` 是 Symbol Link `sites-available` 內的檔案，不是產生一樣的檔案

2020-10-28 06:37 UTC, elct9620 commented on nginx/templates/nginx.conf.erb
> +worker_processes <%= node['nginx']['work_processses'] %>;
新版 Nginx 支援用 `auto` 自動偵測

2020-10-28 06:37 UTC, elct9620 commented on node/attributes/default.rb
> +default['nodejs']['nvm_dir'] = '/.nvm'
這邊用 nvm 安裝的原因是？

2020-10-28 06:37 UTC, elct9620 commented on setup/recipes/default.rb
> +execute 'unzip_awscliv2' do
AWS CLI 應該會內建在 EC2 裡面

2020-10-28 06:37 UTC, elct9620 commented on unicorn/attributes/ruby.rb
> +force_default['unicorn']['bundle_path'] = '/usr/local/rbenv/shims/bundle'
這應該讓系統自動偵測

2020-11-04 10:18 UTC, requiemformemories commented on node/attributes/default.rb
> +default['nodejs']['nvm_dir'] = '/.nvm'
我會考慮用 nvm 安裝是因為想說可以指定比較細的版號，像是 12.16.3 這樣。
但是不是其實可以裝 LTS 或是確定是 12.x 就好了呢？

2020-11-04 10:19 UTC, requiemformemories commented on setup/recipes/default.rb
> +execute 'unzip_awscliv2' do
原來如此，那我把這段拿掉

2020-11-04 10:19 UTC, requiemformemories commented on unicorn/attributes/ruby.rb
> +force_default['unicorn']['bundle_path'] = '/usr/local/rbenv/shims/bundle'
好的 🙆‍♀️

2020-11-04 10:20 UTC, requiemformemories commented on nginx/recipes/unicorn_config.rb
> +%w{sites-available sites-enabled}.each do |dir|
收到，我來改成 symlink

2020-11-04 10:20 UTC, requiemformemories commented on nginx/attributes/default.rb
> +default['nginx']['work_processses'] = '10'
好的，那我拿掉這行

2020-11-04 10:20 UTC, requiemformemories commented on deploy_user/templates/sudoers.d.erb
> +<%= user %> ALL = NOPASSWD: ALL
原來，那我拿掉這行

2020-11-04 10:21 UTC, requiemformemories commented on deploy/recipes/sync_repo.rb
> +execute "chown the app folder (#{app_path}) to deploy user: #{node['deploy']['user']}" do
好的，我來改一下

2020-11-04 10:21 UTC, requiemformemories commented on deploy/recipes/purge_old_releases.rb
> +raise "Number of keep releases must larger than 0" if node['deploy']['keep_releases'] < 1
我還沒改這段，我來把它拿掉

2020-11-04 10:21 UTC, requiemformemories commented on deploy/recipes/deploy.rb
> +#{::File.join('public', node['deploy']['public_output_path'], 'assets')} \
收到 🙇‍♀️

2020-11-04 10:22 UTC, requiemformemories commented on deploy/recipes/deploy.rb
> +              'HOME' => "/home/#{node['deploy']['home']}",
好的 🙆‍♀️

2020-11-04 10:24 UTC, requiemformemories commented on deploy/recipes/deploy.rb
> +bash 'Migrate database' do
不太確定如果是 chef client 要如何確保只有其中一台會 migrate，目前我想到的方法是多加一個 layer，這個 layer 只放一台機器。我在研究一下怎麼調整這個部分

2020-11-04 10:30 UTC, requiemformemories commented on deploy/recipes/deploy.rb
> +  content node['deploy']['environment_variables'].to_h.to_yaml
之前 stack11 是有些設定寫死在 code 裡，有些在 application.yml 裡，有些在 environment_variables 中。然後 environment_variables 會被放到 unicorn.conf 裡（[unicorn::rails#L49](https://github.com/aws/opsworks-cookbooks/blob/e3a4dce4afa3c716547353e7b848496ef180c41e/unicorn/recipes/rails.rb#L49)、 [unicorn.conf.erb#L16](https://github.com/aws/opsworks-cookbooks/blob/e3a4dce4afa3c716547353e7b848496ef180c41e/unicorn/templates/default/unicorn.conf.erb#L16)）
rails server 會吃到 unicorn.conf 跟 application.yml 的設定，但在機器上 rails c 只會吃到 application.yml 的設定，所以才會想要統一放到 application.yml。這邊是不是不應該用 environment_variables？

2020-11-04 10:31 UTC, requiemformemories commented on deploy/recipes/add_rsa_keys.rb
> +directory File.join('home', node['deploy']['home'],'.ssh') do
收到 🙇‍♀️

2020-11-04 10:31 UTC, requiemformemories commented on deploy/recipes/add_known_host.rb
> +  user 'root'
好的 🙇‍♀️

2020-11-04 10:32 UTC, requiemformemories commented on deploy/recipes/deploy.rb
> +raise "Unsupported app_source type: #{app['app_source']['type']}" unless app['app_source']['type'] == 'git'
這是參考 AWS build-in cookbook 的寫法，但他應該寫了很多不太正統的東西，我來研究一下 Chef 官方比較推薦怎麼拋錯誤 🙇‍♀️

2020-11-05 02:02 UTC, elct9620 commented on deploy/recipes/deploy.rb
> +  content node['deploy']['environment_variables'].to_h.to_yaml
不應該把整個環境變數塞進去

2020-11-05 02:03 UTC, elct9620 commented on node/attributes/default.rb
> +default['nodejs']['nvm_dir'] = '/.nvm'
Node.js 對 Rails 來說只是打包工具只需要指定 Stable 版本就夠用了

2020-11-05 02:09 UTC, requiemformemories commented on deploy/recipes/deploy.rb
> +raise "Unsupported app_source type: #{app['app_source']['type']}" unless app['app_source']['type'] == 'git'
https://docs.chef.io/recipes/#end-chef-infra-client-run
找到了， raise exception 確實是 chef 官方有提到讓 client 停止的方式

```
- Use the `raise` keyword to stop a Chef Infra Client run by triggering an unhandled exception
```

2020-11-05 07:43 UTC, requiemformemories commented on deploy/recipes/deploy.rb
> +  content node['deploy']['environment_variables'].to_h.to_yaml
如果是另外有個 node['deploy'][application]['rails_config']，再把這個 config 的內容放進 application.yml 會好一些嗎？

2020-11-05 08:00 UTC, elct9620 commented on deploy/recipes/deploy.rb
> +  content node['deploy']['environment_variables'].to_h.to_yaml
會比這樣塞好一點

2021-02-22 02:23 UTC, requiemformemories commented
功能已經在其他 PR 完成，並已捨棄 unicorn 作為 web server，故 close

2021-02-22 02:23 UTC, closed without merging